# Generated by Django 6.1 on 2026-09-11 10:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_receipt_no_payment_reciept_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reciept_no',
            new_name='receipt_no',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
